---
# tasks file for scap
- ansible.builtin.debug: 
    var: dir_name
- ansible.builtin.debug:
    var: hostname
    
- name: run scap report
  ansible.builtin.shell:
    oscap xccdf eval --profile {{ profile }} \
    --fetch-remote-resources \
    --results-arf /tmp/openscap/{{ dir_name }}_results/arf.xml \
    --report /tmp/openscap/{{ dir_name }}_results/{{ hostname }}_report.html \
    /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml
  register: oscap_result
  become: true

- name: dubug result
  ansible.builtin.debug:
    var: oscap_result