---
# tasks file for scap
- ansible.builtin.debug: 
    var: dir_name
- ansible.builtin.debug:
    var: oscap_hostname

- name: run scap report
  ansible.builtin.shell:
    oscap xccdf eval --profile {{ profile }} \
    --fetch-remote-resources \
    --results-arf {{ results_directory }}/{{ date }}.xml \
    --report {{ results_directory }}/{{ date }}.html \
    {{ scap_content }}
  ignore_errors: true
  register: oscap_result
  become: true
  when: report

- name: Generate Fix
  ansible.builtin.shell:
    oscap xccdf generate fix --profile xccdf_org.ssgproject.content_profile_e8 \
    --fetch-remote-resources {{ date }}.xml > {{ date }}_fix.sh
  args:
      chdir: "{{ results_directory }}"
  ignore_errors: true
  register: oscap_result
  become: true
  when: not report

- name: dubug result da
  ansible.builtin.debug:
    var: oscap_result
